version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env 
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    # env_file: .env
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=parkingbnb.settings
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 parkingbnb.asgi:application"

volumes:
  redis_data:
  postgres_data:
