# Generated by Django 5.2.4 on 2025-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
