# Generated by Django 5.2.4 on 2025-07-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_message_is_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
