# Generated by Django 5.2.4 on 2025-07-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_parkingspace_features_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parkingspace',
            name='marketplace_status_9d7d72_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspace',
            name='marketplace_is_acce_548a97_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspace',
            name='marketplace_owner_i_e34f52_idx',
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['features', 'status', 'owner'], name='marketplace_feature_2a05e4_idx'),
        ),
    ]
