# Generated by Django 5.2.4 on 2025-07-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_parkingspace_marketplace_status_9d7d72_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
