# Generated by Django 5.2.4 on 2025-07-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_paymentmethod_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
