# Generated by Django 5.2.2 on 2025-07-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_message_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='marketplace_created_d40d97_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='marketplace_status_965bdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='marketplace_user_id_8171e6_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='review_left',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_ref',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('ban', 'Ban'), ('warn', 'Warn'), ('refund', 'Refund'), ('edit', 'Edit'), ('resolve_ticket', 'Resolve Ticket'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_space', to='marketplace.parkingspace'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('no-show', 'No Show')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='marketplace.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
