# Generated by Django 5.2.4 on 2025-07-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_booking_marketplace_created_d40d97_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.booking'),
        ),
    ]
