# Generated by Django 5.2.4 on 2025-07-30 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_servicerequest_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
