# Generated by Django 5.2.4 on 2025-07-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_rename_payment_date_payment_created_at_and_more'),
        ('marketplace', '0010_alter_servicerequest_user'),
    ]

    operations = [
    ]
