# Generated by Django 5.2.4 on 2025-08-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_merge_20250731_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.parkingspace'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=12),
        ),
    ]
